//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandlerForMySQL.YDVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis_report_attachment
    {
        public string id { get; set; }
        public string base_path { get; set; }
        public string relative_path { get; set; }
        public string file_extension { get; set; }
        public string file_name { get; set; }
        public string file_from_channel { get; set; }
        public string file_from_channel_name { get; set; }
        public string analysis_report_info_id { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> creat_time { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
