//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHandlerForMySQL.YDVS
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis_report_info
    {
        public string id { get; set; }
        public string train_type { get; set; }
        public string train_no { get; set; }
        public string train_short_name { get; set; }
        public string driver_name { get; set; }
        public string driver_num { get; set; }
        public string ass_driver_name { get; set; }
        public string ass_driver_num { get; set; }
        public Nullable<System.DateTime> event_time { get; set; }
        public Nullable<System.DateTime> analysis_time { get; set; }
        public string analysis_person { get; set; }
        public string analysis_content { get; set; }
        public string event_data_json_str { get; set; }
    }
}
